server {
  listen 80;
  server_tokens off;
  client_max_body_size 5M;
  server_name foodgrams.duckdns.org;
  index index.html;

  location /api/docs/ {
    alias /usr/share/nginx/html/api/docs/;
    index redoc.html;
}

  location / {
    alias /static/;
    try_files $uri $uri/ /index.html;
  }

  location /media/ {
        alias /media/;
    }
}